@Owens.API_HostAddress = https://localhost:7004

POST {{Owens.API_HostAddress}}/member
Content-Type: application/json

{
  "userName": "mjbradvica",
  "email": "mike@mike.com",
  "password": "SuperSecret123!"
}

###
