<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppDesignerFolder>Operators</AppDesignerFolder>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ThemeParks\Stores\**" />
    <EmbeddedResource Remove="ThemeParks\Stores\**" />
    <None Remove="ThemeParks\Stores\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClearDomain.Identity" Version="0.9.8" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="NodaTime" Version="3.3.2" />
  </ItemGroup>
</Project>
