name: Build & Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build Project
        run: dotnet build --no-restore -c Release /warnaserror

      - name: Run Tests
        run: dotnet test --no-restore --no-build -c Release --verbosity normal

      - name: Publish
        run: dotnet publish --no-restore --no-build -c Release source/Owens.API/Owens.API
