name: Build & Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build Project
        run: dotnet build --no-restore -c Release /warnaserror

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.2.0
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: Owens.Tests
          extra-params: "TrustServerCertificate=true;Encrypt=False;"

      - name: Run Tests
        run: dotnet test --no-restore --no-build -c Release --verbosity normal /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=branch

      - name: Publish
        run: dotnet publish --no-restore --no-build -c Release source/Owens.API/Owens.API.csproj
